{% set name = "pydicom" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pydicom/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ffb8d729fcaacf7a3aca243c69fa342305d2696ec59c1f930b2e564d4f1b5fbd

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-deps --no-build-isolation -vv .

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools-scm
    - flit-core >=3.2,<4

  run:
    - python
    - flit-core

test:
  source_files:
    - pydicom/tests
  imports:
    - pydicom
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest pydicom/tests

about:
  home: https://github.com/pydicom/pydicom
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python package for DICOM medical file reading and writing
  description: |
    pydicom is a pure python package for parsing DICOM files. DICOM is a
    standard (https://dicomstandard.org) for communicating medical images and
    related information such as reports and radiotherapy objects.  pydicom
    makes it easy to read these complex files into natural pythonic structures
    for easy manipulation. Modified datasets can be written again to DICOM
    format files. See the `Getting Started
    <https://pydicom.github.io/pydicom/stable/>`_ page for
    installation and basic information, and the `Pydicom User Guide
  doc_url: https://pydicom.github.io/pydicom
  dev_url: https://github.com/pydicom/pydicom

extra:
  recipe-maintainers:
    - darcymason
    - glemaitre
    - arokem
