travis:
  secure:
    BINSTAR_TOKEN: IYO7ibmHfzv3UFrax3KjQcWLX+QyrU4uMib5U61md8jsp8avHQMm5HZVhEyZWsJpHvaEzd3DYDfwvThugNkGx1kuG72SNJxN0EEvQvpesq9UmfyG2b8lYJF89UoyZSw8dy7LaMQ6IlONExC4oFGTHkNry/Ns4nnhmf1jllFllbuTINuqHYg9m6uSu66bbgAVx4VplifutkuS8f9NCh8zY/jg/Jbae7Uj1cE8oIxt1yOZTc0V89AEB6LhxIMaC3uwHrqJbzop1lVsQvuxtwfAYc1e5vbidByHaOKVdrZYZqZPvHT8n+6TZopcXhL7X+lcih70ne4ya5GMGLSg5cJp8qxSj4AYicBMrHtRmE9CABKhyTaH0m4HxMOCnpzJvlfl2UVj4HEssnhl9I8XyMCZlYDOlQyyxFVzECAerxWkOcNcMGuiRHzn2dEHAHqGhhD8paZtXeJdv1oQk0/nd/PRw2rVFW1gT1xT1plwNmcULd4FbGiOJlbx9htno2n0D4vom+Fo2E/Cy6jHUXlfOe1ygA5sPmABUdi1TSvzNZd6o6UQoyVaPI3sHlJ6Dt5ic4emflNY/se4a8fWw1pksOkgKtT8HE0L7wvtcZ6lUEzQmPlIv2ghKoXaVEchOGOGhgUNvqkHYzL5BFXOOIACs9DPLL2kUvdudUJxQQyVOLUW5rA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
