travis:
  secure:
    BINSTAR_TOKEN: NlQEtxQdkKBPhOV53kIfQtSNt9Smwt+Pn+H1zsm2ITwTPFcRQD7sKX74esvUtHKgsevr2qlxwurm21pRHXwP4YLkYMYgSXj8Wl9AUvhfFcWnBIFDFVNZqJsPLzJ8EuXhd5FTcBxo+WrLr7KR6/WVRpdHbXHB9U4cfbD+oKP24H1ifxQhuKEvVaVDuhAeYvCAuiYM3NfVdHfmqJuvv7HvxpiMVcdgkZ+tVF8ZZOyKELFFfCy7OIWiovgRA1EuAfryo5F95YY28IGV6Bk0Nr4dPAiwVOrqkeDNEY8Rud5rjBkRpRbsVRkiLrRLmBTSHqp+eWp63TAG5xIh4yUOVqh/kpfkWVfohBWM3mlcVJCNx0MNhtTdpFD7orUmf5StHO3hX2pygQyCsFbJ34nMKXaEHO3gheKjpoKZOQOSUl1SJNGPKp7k6GbUPtJ9LgefBsaFJDoLigsJ267ic/0Etl5x2+NfDBNjPuIsIl+0bC80vfKTdAJLqgVS6IE8MIz7hW1ul8Wlh1SXBwO2TYoZ7/DY3SK7DU8eCh1pPR4zWiCUEKtpnVemY6UZTtPGqKz09Yddn3y31TrL7jcl4jKmnJeaVyqhv7FfmzdPRPt9w4w2X4MMQL8Of5OOSu/WJQJj+rTWWEZzTnXJbk9pHVs5Hd9nWDk6vKqiKL1tfEbNEgC0tVs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
