travis:
  secure:
    BINSTAR_TOKEN: cBx98bH8D2TXx/McLMPMdtcJnA9hwzSBGxCKAwprxe6wRbplq8BxUll2j1bOXHXTdiMYNmUdiBYqFZeRcmv5GWCAIywnZDC7BUp1NN17hwQqewvsO2xxVKb/V1NlaDoga380zAutWwzsb0/zok8DnCU/ImMLHuI+QCdtrLmMhhdEeCF6Tawmh36bdxrumG8MDn6AP4AP5lv/iY+BrNNePC/v1Xpvd6TBTUfkp6bF2VX+OmyqJn/51N2DNflq/rspAumspaystFHOOI4AGmYAbzuOEkQwJv8qVYsCvyaQSnck+0E7zpwLRejFDQdUIQOmXYcdZAbzkfrWcG2NGS5Q7btieOBBdCy63NcRom1Oon9y9wo4wU0Kvj/ijXbp3swR+hHJ5gRlyfWm/dhBgPRn1chhn7y+E6lBACsDJxA2N6MerX9PaTZq5B7qt93vx0gBk7nJUNeoG134E153fa0oWnLthUvtBnAFFhZTzfnfRAtfee3RQxR7OUAp9CkdLJPvxho1o3sBov3nLSvnHol30Xd0R+mtjnHlkJ1u/Mut+DDXxSaKWWbtzolZA7FUO6JM6atvyLRWZDUYWxXUK2YJ4q35pDZ9rxebCzwy8Au0S9GLvK4cSPSlRFiow7aW7OAWREeeEMKiNzNkJbQRhqHVA/6dx594fAXqFl2/1PmxFaY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
